### PR TITLE
Use .ts extension in relative source imports

### LINKED ISSUE #301: Error loading in Deno
**Describe the bug**
```ts
error: Import 'https://deno.land/x/yaml@v2.0.0-7/src/nodes/Scalar.js' failed: 404 Not Found
    at https://deno.land/x/yaml@v2.0.0-7/src/index.ts:22:0
```

**To Reproduce**
Steps to reproduce the behaviour.
1. Install Deno
2. Run `deno eval "export * as YAML from 'https://deno.land/x/yaml@v2.0.0-7/src/index.ts'"`

**Expected behaviour**
I expect the module to be loaded successfully, no errors

**Versions (please complete the following information):**

- Environment: 
```
deno --version
deno 1.13.0 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```
- `yaml`: `v2.0.0-7`

**Additional context**
Full stack:
```
deno eval "export * as YAML from 'https://deno.land/x/yaml@v2.0.0-7/src/index.ts'"
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/YAMLSeq.js
Download https://deno.land/x/yaml@v2.0.0-7/src/doc/Document.js
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/lexer.js
Download https://deno.land/x/yaml@v2.0.0-7/src/schema/tags
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/parser.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Alias.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Node.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Scalar.js
Download https://deno.land/x/yaml@v2.0.0-7/src/errors.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Pair.js
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/cst.js
Download https://deno.land/x/yaml@v2.0.0-7/src/visit.js
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/line-counter.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/YAMLMap.js
Download https://deno.land/x/yaml@v2.0.0-7/src/public-api.js
Download https://deno.land/x/yaml@v2.0.0-7/src/schema/types
Download https://deno.land/x/yaml@v2.0.0-7/src/options.js
Download https://deno.land/x/yaml@v2.0.0-7/src/compose/composer.js
Download https://deno.land/x/yaml@v2.0.0-7/src/schema/Schema.js
error: Import 'https://deno.land/x/yaml@v2.0.0-7/src/nodes/YAMLSeq.js' failed: 404 Not Found
    at https://deno.land/x/yaml@v2.0.0-7/src/index.ts:24:0
```

The files of course are all typescript in the repository and it fails trying to download them because in the code they're all referencing each other as `.js`. I believe in node it works because its running all the transpiled files after typescript gets them but in Deno that transformation is transparent and it requires the references to be correct.

I know there are a couple of ways to solve this, such as using some auto-esm transpiler, or perhaps you have the JS version published somewhere that I'm not seeing... but I didn't see any documentation in your readme on the way you're intending it to be supported so I thought I'd ask here.

### PR DESCRIPTION
**Pull request by eemeli**
This change adopts the `--rewriteRelativeImportExtensions` option [introduced](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#path-rewriting-for-relative-paths) in Typescript 5.7, and changes all relative paths to use the `.ts` extension.

Due to rollup/plugins#1820, a post-compilation transform is required to get the CLI tool to work right.

An ESLint rule is added to ensure that the `.ts` extension is always there; this may be of interest to others as well: https://github.com/eemeli/yaml/blob/18e611279076efdcd9f4984766d852b4e1f7db99/eslint.config.mjs#L41-L51

Together with explicit `type` on imports & exports, this change fixes #301 and makes the library work directly in Deno. A really simple Deno smoke test is included. It would be nice to get the full test suite to run on Deno as well, as discussed in https://github.com/eemeli/yaml/issues/301#issuecomment-2212045604

Ping @justinmchase & @jeff-hykin: Would you have time to see if this works as expected?

### CODE REVIEW

**Comment by eemeli** [comment]
Also needed to add an `afterDeclarations` transform to drop the `.ts` extensions from the imports in the `.d.ts` files, in order to retain compatibility with older TS versions.

**Comment by eemeli** [comment]
@jeff-hykin Any time for a trial run yet?

I'm looking here for feedback from some actual Deno user to confirm that this does indeed provide a fix for #301, before just presuming so on my own initiative.

**Comment by justinmchase** [comment]
Looks like its working to me, I cloned the repo, checked out the branch and wrote a little script.

image

image

**Comment by justinmchase** [comment]
Also, worth mentioning, but Deno has made a new package repo https://jsr.io which may be worth targeting instead of / in addition to deno land.

It's not much different in terms of what you publish, just done with a github action. 

Here is a pretty minimal example repo I created for reference: https://github.com/justinmchase/type/blob/main/.github/workflows/publish.yml

**Pull request merged**
